In [ ]:
Esercizio 
Abbiamo una lista di liste: 
mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]] 
Che tipo di struttura dati o matematica potrebbe rappresentare? 
Notare che tutte le liste "interne" sono della stessa dimensione.
Come facciamo per accedere ad un elemento in particolare?

In [ ]:
RISPOSTE:
La struttura dati rappresenta una matrice bidimensionale, 
dove ogni lista interna corrisponde a una riga della matrice. 
Gli elementi sono organizzati in righe e colonne, simili a una griglia numerata.


Per accedere ad un elemento in particolare:

In [5]:
mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
print(mat[1][4])

9


In [6]:
import math

In [7]:
math.sin(19)

0.14987720966295234

In [8]:
math.cos(19)

0.9887046181866692

In [9]:
math.factorial(19)

121645100408832000

In [12]:
math.pi

3.141592653589793

In [ ]:
La variabile pi è il valore numerico di pi greco

In [13]:
math.degrees(math.pi)

180.0

In [15]:
help(math.degrees)

Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



In [40]:
import numpy as np
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
np.array(lst)


array([2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100,
       5350])

In [42]:
import numpy as np

# Lista delle vendite mensili
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]

# Trasformazione della lista in un array NumPy
lst = np.array(lst)

# Vendita massima mensile
vendita_massima = np.max(lst)
print("Vendita massima mensile:", vendita_massima)

# Vendita minima mensile
vendita_minima = np.min(lst)
print("Vendita minima mensile:", vendita_minima)

# Vendite mensili maggiori di 4999 oggetti
vendite_maggiori_4999 = lst[lst > 4999]
print("Vendite mensili maggiori di 4999 oggetti:", vendite_maggiori_4999)
print("Numero di vendite mensili maggiori di 4999 oggetti:", len(vendite_maggiori_4999))

# Vendite mensili minori di 3000 oggetti
vendite_minori_3000 = lst[lst < 3000]
print("Vendite mensili minori di 3000 oggetti:", vendite_minori_3000)

# Media delle vendite mensili
media_vendite = np.mean(lst)
print("Media delle vendite mensili:", media_vendite)


Vendita massima mensile: 8150
Vendita minima mensile: 1280
Vendite mensili maggiori di 4999 oggetti: [5500 7200 6410 8150 7100 5350]
Numero di vendite mensili maggiori di 4999 oggetti: 6
Vendite mensili minori di 3000 oggetti: [2000 1280 1900 2500]
Media delle vendite mensili: 4634.166666666667


In [50]:
import pandas as pd
fatturati_dict = {1997: 12_000, 1998: 15_000, 
                  1999: 20_000, 2000: 23_000,
                  2001: 25_000, 2002: 17_000, 
                  2003: 14_000, 2004: 21_000}
fatturati_series = pd.Series([12_000, 15_000, 
                              20_000, 23_000, 
                              25_000, 17_000,
                              14_000, 21_000], index=range(1997, 2005))


fatturati_series[1997] 


12000

In [ ]:
Dunque qual è la differenza tra i due tipi di dato?
La principale differenza tra un dizionario e un oggetto Series di pandas risiede nella loro struttura e nell'accesso ai dati:
il dizionario associa chiavi a valori.
l'oggetto Series è una struttura dati unidimensionale che contiene valori ordinati associati a un indice


Cosa potremmo fare con la Series che non possiamo fare con il dizionario?
Con un oggetto Series di pandas, possiamo eseguire operazioni di analisi dati avanzate come indicizzazione avanzata,
operazioni vettorialiali, calcolo di statistiche e aggregazioni, e visualizzazione dei dati, 
che non sono disponibili direttamente con un dizionario.

In [51]:
import numpy as np

stipendi = np.array([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000])

# Raddoppiare gli stipendi utilizzando un ciclo for
for i in range(len(stipendi)):
    stipendi[i] *= 2

print(stipendi)

[ 200  400  600  800 1000 1200 1400 1600 1800 2000]


In [54]:
import numpy as np

stipendi = np.array([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000])

stipendi *= 2
print(stipendi)

[ 200  400  600  800 1000 1200 1400 1600 1800 2000]
